# WEDNESDAY 10TH SEP CLASS

### File input/output
- we use with in python in file handling ,,,, ant this is to avoid forgetting closing the file.

#### Wednesday class
##### To write into a file:
    with open("sample.csv","w") as file:
        file.write("HELLO WORLD!")

##### To read a file as csv;
    with open("sample.csv","r") as file:
        content = file.read
        print(content)

##### Files into dataframes
    import pandas as pd
    df= pd.read_csv(r"sample.csv")
    df.head()

##### Copying data from one file to another;
    df.to_csv("sample.csv", index = False)

##### Displaying information of a dataset;
    df.info()

##### Renaming a column heading;
    df.rename(columns={"Ratingd":"Ratings"}, inplace= True)
    df.head()

##### Checking for missing values;
    df.isnull().sum()
    
##### Dropping values;
    df = df.drop(columns=["Review","Ratingd"],axis=1)
    df.head()

##### Reading file in dataframes;
    df = pd.read_csv(r"sample.csv")
    df.head()
    
##### Grouping by;
    data.groupby("Pclass")["fare"].sum()

##### Displaying KPI'S;
    data.describe()

##### Copying from csv to csv without pandas;(NOTE THE INDENTATION)
- WRITE THE DATA IN EXCEL FILE TO SAMPLE.CSV


###### Step 1: Open the source file (Excel.csv) for reading
    with open('Excel_jumia 1.csv', mode='r', newline='', encoding='utf-8') as infile:
        reader = csv.reader(infile)

###### Step 2: Open the destination file (sample.csv) for writing
        with open('sample.csv', mode='w', newline='', encoding='utf-8') as outfile:
            writer = csv.writer(outfile)

###### Step 3: Copy each row from the source to the destination
            for row in reader:
                writer.writerow(row)

--- *look into other file functions eg "r", "w"

In [ ]:
# "W" IS FOR writing into a file
# "r" is for reading files
with open("sample.txt","w") as file:
    file.write ("Hello world!")

In [1]:
with open("tested.csv","r") as file:
    content = file.read()
    print(content)

PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,,Q
893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47,1,0,363272,7,,S
894,0,2,"Myles, Mr. Thomas Francis",male,62,0,0,240276,9.6875,,Q
895,0,3,"Wirz, Mr. Albert",male,27,0,0,315154,8.6625,,S
896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22,1,1,3101298,12.2875,,S
897,0,3,"Svensson, Mr. Johan Cervin",male,14,0,0,7538,9.225,,S
898,1,3,"Connolly, Miss. Kate",female,30,0,0,330972,7.6292,,Q
899,0,2,"Caldwell, Mr. Albert Francis",male,26,1,1,248738,29,,S
900,1,3,"Abrahim, Mrs. Joseph (Sophie Halaut Easu)",female,18,0,0,2657,7.2292,,C
901,0,3,"Davies, Mr. John Samuel",male,21,2,0,A/4 48871,24.15,,S
902,0,3,"Ilieff, Mr. Ylio",male,,0,0,349220,7.8958,,S
903,0,1,"Jones, Mr. Charles Cresson",male,46,0,0,694,26,,S
904,1,1,"Snyder, Mrs. John Pillsbury (Nelle Stevenson)",female,23,1,0,21228,82.2667,B45,S
905,0,2,"Howard, Mr. Benjamin",male,63,1,0,24065,26,,S
906,1,1,"Chaffee, Mrs. Herbert Fuller (Carrie Constance Toogood)",female,47,1,0,W.E.P. 5734,61.175,E31,S
907,1,2,"del Carlo, Mrs. Sebastiano (Argenia Genovesi)",female,24,1,0,SC/PARIS 2167,27.7208,,C
908,0,2,"Keane, Mr. Daniel",male,35,0,0,233734,12.35,,Q
909,0,3,"Assaf, Mr. Gerios",male,21,0,0,2692,7.225,,C
910,1,3,"Ilmakangas, Miss. Ida Livija",female,27,1,0,STON/O2. 3101270,7.925,,S
911,1,3,"Assaf Khalil, Mrs. Mariana (Miriam"")""",female,45,0,0,2696,7.225,,C
912,0,1,"Rothschild, Mr. Martin",male,55,1,0,PC 17603,59.4,,C
913,0,3,"Olsen, Master. Artur Karl",male,9,0,1,C 17368,3.1708,,S
914,1,1,"Flegenheim, Mrs. Alfred (Antoinette)",female,,0,0,PC 17598,31.6833,,S
915,0,1,"Williams, Mr. Richard Norris II",male,21,0,1,PC 17597,61.3792,,C
916,1,1,"Ryerson, Mrs. Arthur Larned (Emily Maria Borie)",female,48,1,3,PC 17608,262.375,B57 B59 B63 B66,C
917,0,3,"Robins, Mr. Alexander A",male,50,1,0,A/5. 3337,14.5,,S
918,1,1,"Ostby, Miss. Helene Ragnhild",female,22,0,1,113509,61.9792,B36,C
919,0,3,"Daher, Mr. Shedid",male,22.5,0,0,2698,7.225,,C
920,0,1,"Brady, Mr. John Bertram",male,41,0,0,113054,30.5,A21,S
921,0,3,"Samaan, Mr. Elias",male,,2,0,2662,21.6792,,C
922,0,2,"Louch, Mr. Charles Alexander",male,50,1,0,SC/AH 3085,26,,S
923,0,2,"Jefferys, Mr. Clifford Thomas",male,24,2,0,C.A. 31029,31.5,,S
924,1,3,"Dean, Mrs. Bertram (Eva Georgetta Light)",female,33,1,2,C.A. 2315,20.575,,S
925,1,3,"Johnston, Mrs. Andrew G (Elizabeth Lily"" Watson)""",female,,1,2,W./C. 6607,23.45,,S
926,0,1,"Mock, Mr. Philipp Edmund",male,30,1,0,13236,57.75,C78,C
927,0,3,"Katavelas, Mr. Vassilios (Catavelas Vassilios"")""",male,18.5,0,0,2682,7.2292,,C
928,1,3,"Roth, Miss. Sarah A",female,,0,0,342712,8.05,,S
929,1,3,"Cacic, Miss. Manda",female,21,0,0,315087,8.6625,,S
930,0,3,"Sap, Mr. Julius",male,25,0,0,345768,9.5,,S
931,0,3,"Hee, Mr. Ling",male,,0,0,1601,56.4958,,S
932,0,3,"Karun, Mr. Franz",male,39,0,1,349256,13.4167,,C
933,0,1,"Franklin, Mr. Thomas Parham",male,,0,0,113778,26.55,D34,S
934,0,3,"Goldsmith, Mr. Nathan",male,41,0,0,SOTON/O.Q. 3101263,7.85,,S
935,1,2,"Corbett, Mrs. Walter H (Irene Colvin)",female,30,0,0,237249,13,,S
936,1,1,"Kimball, Mrs. Edwin Nelson Jr (Gertrude Parsons)",female,45,1,0,11753,52.5542,D19,S
937,0,3,"Peltomaki, Mr. Nikolai Johannes",male,25,0,0,STON/O 2. 3101291,7.925,,S
938,0,1,"Chevre, Mr. Paul Romaine",male,45,0,0,PC 17594,29.7,A9,C
939,0,3,"Shaughnessy, Mr. Patrick",male,,0,0,370374,7.75,,Q
940,1,1,"Bucknell, Mrs. William Robert (Emma Eliza Ward)",female,60,0,0,11813,76.2917,D15,C
941,1,3,"Coutts, Mrs. William (Winnie Minnie"" Treanor)""",female,36,0,2,C.A. 37671,15.9,,S
942,0,1,"Smith, Mr. Lucien Philip",male,24,1,0,13695,60,C31,S
943,0,2,"Pulbaum, Mr. Franz",male,27,0,0,SC/PARIS 2168,15.0333,,C
944,1,2,"Hocking, Miss. Ellen Nellie""""",female,20,2,1,29105,23,,S
945,1,1,"Fortune, Miss. Ethel Flora",female,28,3,2,19950,263,C23 C25 C27,S
946,0,2,"Mangiavacchi, Mr. Serafino Emilio",male,,0,0,SC/A.3 2861,15.5792,,C
947,0,3,"Rice, Master. Albert",male,10,4,1,382652,29.125,,Q
948,0,3,"Cor, Mr. Bartol",male,35,0,0,349230,7.8958,,S
949,0,3,"Abelseth, Mr. Olaus Jorgensen",male,25,0,0,348122,7.65,F G63,S
950,0,3,"Davison, Mr. Thomas Henry",male,,1,0,386525,16.1,,S
951,1,1,"Chaudanson, Miss. Victorine",female,36,0,0,PC 17608,262.375,B61,C
952,0,3,"Dika, Mr. Mirko",male,17,0,0,349232,7.8958,,S
953,0,2,"McCrae, Mr. Arthur Gordon",male,32,0,0,237216,13.5,,S
954,0,3,"Bjorklund, Mr. Ernst Herbert",male,18,0,0,347090,7.75,,S
955,1,3,"Bradley, Miss. Bridget Delia",female,22,0,0,334914,7.725,,Q
956,0,1,"Ryerson, Master. John Borie",male,13,2,2,PC 17608,262.375,B57 B59 B63 B66,C
957,1,2,"Corey, Mrs. Percy C (Mary Phyllis Elizabeth Miller)",female,,0,0,F.C.C. 13534,21,,S
958,1,3,"Burns, Miss. Mary Delia",female,18,0,0,330963,7.8792,,Q
959,0,1,"Moore, Mr. Clarence Bloomfield",male,47,0,0,113796,42.4,,S
960,0,1,"Tucker, Mr. Gilbert Milligan Jr",male,31,0,0,2543,28.5375,C53,C
961,1,1,"Fortune, Mrs. Mark (Mary McDougald)",female,60,1,4,19950,263,C23 C25 C27,S
962,1,3,"Mulvihill, Miss. Bertha E",female,24,0,0,382653,7.75,,Q
963,0,3,"Minkoff, Mr. Lazar",male,21,0,0,349211,7.8958,,S
964,1,3,"Nieminen, Miss. Manta Josefina",female,29,0,0,3101297,7.925,,S
965,0,1,"Ovies y Rodriguez, Mr. Servando",male,28.5,0,0,PC 17562,27.7208,D43,C
966,1,1,"Geiger, Miss. Amalie",female,35,0,0,113503,211.5,C130,C
967,0,1,"Keeping, Mr. Edwin",male,32.5,0,0,113503,211.5,C132,C
968,0,3,"Miles, Mr. Frank",male,,0,0,359306,8.05,,S
969,1,1,"Cornell, Mrs. Robert Clifford (Malvina Helen Lamson)",female,55,2,0,11770,25.7,C101,S
970,0,2,"Aldworth, Mr. Charles Augustus",male,30,0,0,248744,13,,S
971,1,3,"Doyle, Miss. Elizabeth",female,24,0,0,368702,7.75,,Q
972,0,3,"Boulos, Master. Akar",male,6,1,1,2678,15.2458,,C
973,0,1,"Straus, Mr. Isidor",male,67,1,0,PC 17483,221.7792,C55 C57,S
974,0,1,"Case, Mr. Howard Brown",male,49,0,0,19924,26,,S
975,0,3,"Demetri, Mr. Marinko",male,,0,0,349238,7.8958,,S
976,0,2,"Lamb, Mr. John Joseph",male,,0,0,240261,10.7083,,Q
977,0,3,"Khalil, Mr. Betros",male,,1,0,2660,14.4542,,C
978,1,3,"Barry, Miss. Julia",female,27,0,0,330844,7.8792,,Q
979,1,3,"Badman, Miss. Emily Louisa",female,18,0,0,A/4 31416,8.05,,S
980,1,3,"O'Donoghue, Ms. Bridget",female,,0,0,364856,7.75,,Q
981,0,2,"Wells, Master. Ralph Lester",male,2,1,1,29103,23,,S
982,1,3,"Dyker, Mrs. Adolf Fredrik (Anna Elisabeth Judith Andersson)",female,22,1,0,347072,13.9,,S
983,0,3,"Pedersen, Mr. Olaf",male,,0,0,345498,7.775,,S
984,1,1,"Davidson, Mrs. Thornton (Orian Hays)",female,27,1,2,F.C. 12750,52,B71,S
985,0,3,"Guest, Mr. Robert",male,,0,0,376563,8.05,,S
986,0,1,"Birnbaum, Mr. Jakob",male,25,0,0,13905,26,,C
987,0,3,"Tenglin, Mr. Gunnar Isidor",male,25,0,0,350033,7.7958,,S
988,1,1,"Cavendish, Mrs. Tyrell William (Julia Florence Siegel)",female,76,1,0,19877,78.85,C46,S
989,0,3,"Makinen, Mr. Kalle Edvard",male,29,0,0,STON/O 2. 3101268,7.925,,S
990,1,3,"Braf, Miss. Elin Ester Maria",female,20,0,0,347471,7.8542,,S
991,0,3,"Nancarrow, Mr. William Henry",male,33,0,0,A./5. 3338,8.05,,S
992,1,1,"Stengel, Mrs. Charles Emil Henry (Annie May Morris)",female,43,1,0,11778,55.4417,C116,C
993,0,2,"Weisz, Mr. Leopold",male,27,1,0,228414,26,,S
994,0,3,"Foley, Mr. William",male,,0,0,365235,7.75,,Q
995,0,3,"Johansson Palmquist, Mr. Oskar Leander",male,26,0,0,347070,7.775,,S
996,1,3,"Thomas, Mrs. Alexander (Thamine Thelma"")""",female,16,1,1,2625,8.5167,,C
997,0,3,"Holthen, Mr. Johan Martin",male,28,0,0,C 4001,22.525,,S
998,0,3,"Buckley, Mr. Daniel",male,21,0,0,330920,7.8208,,Q
999,0,3,"Ryan, Mr. Edward",male,,0,0,383162,7.75,,Q
1000,0,3,"Willer, Mr. Aaron (Abi Weller"")""",male,,0,0,3410,8.7125,,S
1001,0,2,"Swane, Mr. George",male,18.5,0,0,248734,13,F,S
1002,0,2,"Stanton, Mr. Samuel Ward",male,41,0,0,237734,15.0458,,C
1003,1,3,"Shine, Miss. Ellen Natalia",female,,0,0,330968,7.7792,,Q
1004,1,1,"Evans, Miss. Edith Corse",female,36,0,0,PC 17531,31.6792,A29,C
1005,1,3,"Buckley, Miss. Katherine",female,18.5,0,0,329944,7.2833,,Q
1006,1,1,"Straus, Mrs. Isidor (Rosalie Ida Blun)",female,63,1,0,PC 17483,221.7792,C55 C57,S
1007,0,3,"Chronopoulos, Mr. Demetrios",male,18,1,0,2680,14.4542,,C
1008,0,3,"Thomas, Mr. John",male,,0,0,2681,6.4375,,C
1009,1,3,"Sandstrom, Miss. Beatrice Irene",female,1,1,1,PP 9549,16.7,G6,S
1010,0,1,"Beattie, Mr. Thomson",male,36,0,0,13050,75.2417,C6,C
1011,1,2,"Chapman, Mrs. John Henry (Sara Elizabeth Lawry)",female,29,1,0,SC/AH 29037,26,,S
1012,1,2,"Watt, Miss. Bertha J",female,12,0,0,C.A. 33595,15.75,,S
1013,0,3,"Kiernan, Mr. John",male,,1,0,367227,7.75,,Q
1014,1,1,"Schabert, Mrs. Paul (Emma Mock)",female,35,1,0,13236,57.75,C28,C
1015,0,3,"Carver, Mr. Alfred John",male,28,0,0,392095,7.25,,S
1016,0,3,"Kennedy, Mr. John",male,,0,0,368783,7.75,,Q
1017,1,3,"Cribb, Miss. Laura Alice",female,17,0,1,371362,16.1,,S
1018,0,3,"Brobeck, Mr. Karl Rudolf",male,22,0,0,350045,7.7958,,S
1019,1,3,"McCoy, Miss. Alicia",female,,2,0,367226,23.25,,Q
1020,0,2,"Bowenur, Mr. Solomon",male,42,0,0,211535,13,,S
1021,0,3,"Petersen, Mr. Marius",male,24,0,0,342441,8.05,,S
1022,0,3,"Spinner, Mr. Henry John",male,32,0,0,STON/OQ. 369943,8.05,,S
1023,0,1,"Gracie, Col. Archibald IV",male,53,0,0,113780,28.5,C51,C
1024,1,3,"Lefebre, Mrs. Frank (Frances)",female,,0,4,4133,25.4667,,S
1025,0,3,"Thomas, Mr. Charles P",male,,1,0,2621,6.4375,,C
1026,0,3,"Dintcheff, Mr. Valtcho",male,43,0,0,349226,7.8958,,S
1027,0,3,"Carlsson, Mr. Carl Robert",male,24,0,0,350409,7.8542,,S
1028,0,3,"Zakarian, Mr. Mapriededer",male,26.5,0,0,2656,7.225,,C
1029,0,2,"Schmidt, Mr. August",male,26,0,0,248659,13,,S
1030,1,3,"Drapkin, Miss. Jennie",female,23,0,0,SOTON/OQ 392083,8.05,,S
1031,0,3,"Goodwin, Mr. Charles Frederick",male,40,1,6,CA 2144,46.9,,S
1032,1,3,"Goodwin, Miss. Jessie Allis",female,10,5,2,CA 2144,46.9,,S
1033,1,1,"Daniels, Miss. Sarah",female,33,0,0,113781,151.55,,S
1034,0,1,"Ryerson, Mr. Arthur Larned",male,61,1,3,PC 17608,262.375,B57 B59 B63 B66,C
1035,0,2,"Beauchamp, Mr. Henry James",male,28,0,0,244358,26,,S
1036,0,1,"Lindeberg-Lind, Mr. Erik Gustaf (Mr Edward Lingrey"")""",male,42,0,0,17475,26.55,,S
1037,0,3,"Vander Planke, Mr. Julius",male,31,3,0,345763,18,,S
1038,0,1,"Hilliard, Mr. Herbert Henry",male,,0,0,17463,51.8625,E46,S
1039,0,3,"Davies, Mr. Evan",male,22,0,0,SC/A4 23568,8.05,,S
1040,0,1,"Crafton, Mr. John Bertram",male,,0,0,113791,26.55,,S
1041,0,2,"Lahtinen, Rev. William",male,30,1,1,250651,26,,S
1042,1,1,"Earnshaw, Mrs. Boulton (Olive Potter)",female,23,0,1,11767,83.1583,C54,C
1043,0,3,"Matinoff, Mr. Nicola",male,,0,0,349255,7.8958,,C
1044,0,3,"Storey, Mr. Thomas",male,60.5,0,0,3701,,,S
1045,1,3,"Klasen, Mrs. (Hulda Kristina Eugenia Lofqvist)",female,36,0,2,350405,12.1833,,S
1046,0,3,"Asplund, Master. Filip Oscar",male,13,4,2,347077,31.3875,,S
1047,0,3,"Duquemin, Mr. Joseph",male,24,0,0,S.O./P.P. 752,7.55,,S
1048,1,1,"Bird, Miss. Ellen",female,29,0,0,PC 17483,221.7792,C97,S
1049,1,3,"Lundin, Miss. Olga Elida",female,23,0,0,347469,7.8542,,S
1050,0,1,"Borebank, Mr. John James",male,42,0,0,110489,26.55,D22,S
1051,1,3,"Peacock, Mrs. Benjamin (Edith Nile)",female,26,0,2,SOTON/O.Q. 3101315,13.775,,S
1052,1,3,"Smyth, Miss. Julia",female,,0,0,335432,7.7333,,Q
1053,0,3,"Touma, Master. Georges Youssef",male,7,1,1,2650,15.2458,,C
1054,1,2,"Wright, Miss. Marion",female,26,0,0,220844,13.5,,S
1055,0,3,"Pearce, Mr. Ernest",male,,0,0,343271,7,,S
1056,0,2,"Peruschitz, Rev. Joseph Maria",male,41,0,0,237393,13,,S
1057,1,3,"Kink-Heilmann, Mrs. Anton (Luise Heilmann)",female,26,1,1,315153,22.025,,S
1058,0,1,"Brandeis, Mr. Emil",male,48,0,0,PC 17591,50.4958,B10,C
1059,0,3,"Ford, Mr. Edward Watson",male,18,2,2,W./C. 6608,34.375,,S
1060,1,1,"Cassebeer, Mrs. Henry Arthur Jr (Eleanor Genevieve Fosdick)",female,,0,0,17770,27.7208,,C
1061,1,3,"Hellstrom, Miss. Hilda Maria",female,22,0,0,7548,8.9625,,S
1062,0,3,"Lithman, Mr. Simon",male,,0,0,S.O./P.P. 251,7.55,,S
1063,0,3,"Zakarian, Mr. Ortin",male,27,0,0,2670,7.225,,C
1064,0,3,"Dyker, Mr. Adolf Fredrik",male,23,1,0,347072,13.9,,S
1065,0,3,"Torfa, Mr. Assad",male,,0,0,2673,7.2292,,C
1066,0,3,"Asplund, Mr. Carl Oscar Vilhelm Gustafsson",male,40,1,5,347077,31.3875,,S
1067,1,2,"Brown, Miss. Edith Eileen",female,15,0,2,29750,39,,S
1068,1,2,"Sincock, Miss. Maude",female,20,0,0,C.A. 33112,36.75,,S
1069,0,1,"Stengel, Mr. Charles Emil Henry",male,54,1,0,11778,55.4417,C116,C
1070,1,2,"Becker, Mrs. Allen Oliver (Nellie E Baumgardner)",female,36,0,3,230136,39,F4,S
1071,1,1,"Compton, Mrs. Alexander Taylor (Mary Eliza Ingersoll)",female,64,0,2,PC 17756,83.1583,E45,C
1072,0,2,"McCrie, Mr. James Matthew",male,30,0,0,233478,13,,S
1073,0,1,"Compton, Mr. Alexander Taylor Jr",male,37,1,1,PC 17756,83.1583,E52,C
1074,1,1,"Marvin, Mrs. Daniel Warner (Mary Graham Carmichael Farquarson)",female,18,1,0,113773,53.1,D30,S
1075,0,3,"Lane, Mr. Patrick",male,,0,0,7935,7.75,,Q
1076,1,1,"Douglas, Mrs. Frederick Charles (Mary Helene Baxter)",female,27,1,1,PC 17558,247.5208,B58 B60,C
1077,0,2,"Maybery, Mr. Frank Hubert",male,40,0,0,239059,16,,S
1078,1,2,"Phillips, Miss. Alice Frances Louisa",female,21,0,1,S.O./P.P. 2,21,,S
1079,0,3,"Davies, Mr. Joseph",male,17,2,0,A/4 48873,8.05,,S
1080,1,3,"Sage, Miss. Ada",female,,8,2,CA. 2343,69.55,,S
1081,0,2,"Veal, Mr. James",male,40,0,0,28221,13,,S
1082,0,2,"Angle, Mr. William A",male,34,1,0,226875,26,,S
1083,0,1,"Salomon, Mr. Abraham L",male,,0,0,111163,26,,S
1084,0,3,"van Billiard, Master. Walter John",male,11.5,1,1,A/5. 851,14.5,,S
1085,0,2,"Lingane, Mr. John",male,61,0,0,235509,12.35,,Q
1086,0,2,"Drew, Master. Marshall Brines",male,8,0,2,28220,32.5,,S
1087,0,3,"Karlsson, Mr. Julius Konrad Eugen",male,33,0,0,347465,7.8542,,S
1088,0,1,"Spedden, Master. Robert Douglas",male,6,0,2,16966,134.5,E34,C
1089,1,3,"Nilsson, Miss. Berta Olivia",female,18,0,0,347066,7.775,,S
1090,0,2,"Baimbrigge, Mr. Charles Robert",male,23,0,0,C.A. 31030,10.5,,S
1091,1,3,"Rasmussen, Mrs. (Lena Jacobsen Solvang)",female,,0,0,65305,8.1125,,S
1092,1,3,"Murphy, Miss. Nora",female,,0,0,36568,15.5,,Q
1093,0,3,"Danbom, Master. Gilbert Sigvard Emanuel",male,0.33,0,2,347080,14.4,,S
1094,0,1,"Astor, Col. John Jacob",male,47,1,0,PC 17757,227.525,C62 C64,C
1095,1,2,"Quick, Miss. Winifred Vera",female,8,1,1,26360,26,,S
1096,0,2,"Andrew, Mr. Frank Thomas",male,25,0,0,C.A. 34050,10.5,,S
1097,0,1,"Omont, Mr. Alfred Fernand",male,,0,0,F.C. 12998,25.7417,,C
1098,1,3,"McGowan, Miss. Katherine",female,35,0,0,9232,7.75,,Q
1099,0,2,"Collett, Mr. Sidney C Stuart",male,24,0,0,28034,10.5,,S
1100,1,1,"Rosenbaum, Miss. Edith Louise",female,33,0,0,PC 17613,27.7208,A11,C
1101,0,3,"Delalic, Mr. Redjo",male,25,0,0,349250,7.8958,,S
1102,0,3,"Andersen, Mr. Albert Karvin",male,32,0,0,C 4001,22.525,,S
1103,0,3,"Finoli, Mr. Luigi",male,,0,0,SOTON/O.Q. 3101308,7.05,,S
1104,0,2,"Deacon, Mr. Percy William",male,17,0,0,S.O.C. 14879,73.5,,S
1105,1,2,"Howard, Mrs. Benjamin (Ellen Truelove Arman)",female,60,1,0,24065,26,,S
1106,1,3,"Andersson, Miss. Ida Augusta Margareta",female,38,4,2,347091,7.775,,S
1107,0,1,"Head, Mr. Christopher",male,42,0,0,113038,42.5,B11,S
1108,1,3,"Mahon, Miss. Bridget Delia",female,,0,0,330924,7.8792,,Q
1109,0,1,"Wick, Mr. George Dennick",male,57,1,1,36928,164.8667,,S
1110,1,1,"Widener, Mrs. George Dunton (Eleanor Elkins)",female,50,1,1,113503,211.5,C80,C
1111,0,3,"Thomson, Mr. Alexander Morrison",male,,0,0,32302,8.05,,S
1112,1,2,"Duran y More, Miss. Florentina",female,30,1,0,SC/PARIS 2148,13.8583,,C
1113,0,3,"Reynolds, Mr. Harold J",male,21,0,0,342684,8.05,,S
1114,1,2,"Cook, Mrs. (Selena Rogers)",female,22,0,0,W./C. 14266,10.5,F33,S
1115,0,3,"Karlsson, Mr. Einar Gervasius",male,21,0,0,350053,7.7958,,S
1116,1,1,"Candee, Mrs. Edward (Helen Churchill Hungerford)",female,53,0,0,PC 17606,27.4458,,C
1117,1,3,"Moubarek, Mrs. George (Omine Amenia"" Alexander)""",female,,0,2,2661,15.2458,,C
1118,0,3,"Asplund, Mr. Johan Charles",male,23,0,0,350054,7.7958,,S
1119,1,3,"McNeill, Miss. Bridget",female,,0,0,370368,7.75,,Q
1120,0,3,"Everett, Mr. Thomas James",male,40.5,0,0,C.A. 6212,15.1,,S
1121,0,2,"Hocking, Mr. Samuel James Metcalfe",male,36,0,0,242963,13,,S
1122,0,2,"Sweet, Mr. George Frederick",male,14,0,0,220845,65,,S
1123,1,1,"Willard, Miss. Constance",female,21,0,0,113795,26.55,,S
1124,0,3,"Wiklund, Mr. Karl Johan",male,21,1,0,3101266,6.4958,,S
1125,0,3,"Linehan, Mr. Michael",male,,0,0,330971,7.8792,,Q
1126,0,1,"Cumings, Mr. John Bradley",male,39,1,0,PC 17599,71.2833,C85,C
1127,0,3,"Vendel, Mr. Olof Edvin",male,20,0,0,350416,7.8542,,S
1128,0,1,"Warren, Mr. Frank Manley",male,64,1,0,110813,75.25,D37,C
1129,0,3,"Baccos, Mr. Raffull",male,20,0,0,2679,7.225,,C
1130,1,2,"Hiltunen, Miss. Marta",female,18,1,1,250650,13,,S
1131,1,1,"Douglas, Mrs. Walter Donald (Mahala Dutton)",female,48,1,0,PC 17761,106.425,C86,C
1132,1,1,"Lindstrom, Mrs. Carl Johan (Sigrid Posse)",female,55,0,0,112377,27.7208,,C
1133,1,2,"Christy, Mrs. (Alice Frances)",female,45,0,2,237789,30,,S
1134,0,1,"Spedden, Mr. Frederic Oakley",male,45,1,1,16966,134.5,E34,C
1135,0,3,"Hyman, Mr. Abraham",male,,0,0,3470,7.8875,,S
1136,0,3,"Johnston, Master. William Arthur Willie""""",male,,1,2,W./C. 6607,23.45,,S
1137,0,1,"Kenyon, Mr. Frederick R",male,41,1,0,17464,51.8625,D21,S
1138,1,2,"Karnes, Mrs. J Frank (Claire Bennett)",female,22,0,0,F.C.C. 13534,21,,S
1139,0,2,"Drew, Mr. James Vivian",male,42,1,1,28220,32.5,,S
1140,1,2,"Hold, Mrs. Stephen (Annie Margaret Hill)",female,29,1,0,26707,26,,S
1141,1,3,"Khalil, Mrs. Betros (Zahie Maria"" Elias)""",female,,1,0,2660,14.4542,,C
1142,1,2,"West, Miss. Barbara J",female,0.92,1,2,C.A. 34651,27.75,,S
1143,0,3,"Abrahamsson, Mr. Abraham August Johannes",male,20,0,0,SOTON/O2 3101284,7.925,,S
1144,0,1,"Clark, Mr. Walter Miller",male,27,1,0,13508,136.7792,C89,C
1145,0,3,"Salander, Mr. Karl Johan",male,24,0,0,7266,9.325,,S
1146,0,3,"Wenzel, Mr. Linhart",male,32.5,0,0,345775,9.5,,S
1147,0,3,"MacKay, Mr. George William",male,,0,0,C.A. 42795,7.55,,S
1148,0,3,"Mahon, Mr. John",male,,0,0,AQ/4 3130,7.75,,Q
1149,0,3,"Niklasson, Mr. Samuel",male,28,0,0,363611,8.05,,S
1150,1,2,"Bentham, Miss. Lilian W",female,19,0,0,28404,13,,S
1151,0,3,"Midtsjo, Mr. Karl Albert",male,21,0,0,345501,7.775,,S
1152,0,3,"de Messemaeker, Mr. Guillaume Joseph",male,36.5,1,0,345572,17.4,,S
1153,0,3,"Nilsson, Mr. August Ferdinand",male,21,0,0,350410,7.8542,,S
1154,1,2,"Wells, Mrs. Arthur Henry (Addie"" Dart Trevaskis)""",female,29,0,2,29103,23,,S
1155,1,3,"Klasen, Miss. Gertrud Emilia",female,1,1,1,350405,12.1833,,S
1156,0,2,"Portaluppi, Mr. Emilio Ilario Giuseppe",male,30,0,0,C.A. 34644,12.7375,,C
1157,0,3,"Lyntakoff, Mr. Stanko",male,,0,0,349235,7.8958,,S
1158,0,1,"Chisholm, Mr. Roderick Robert Crispin",male,,0,0,112051,0,,S
1159,0,3,"Warren, Mr. Charles William",male,,0,0,C.A. 49867,7.55,,S
1160,1,3,"Howard, Miss. May Elizabeth",female,,0,0,A. 2. 39186,8.05,,S
1161,0,3,"Pokrnic, Mr. Mate",male,17,0,0,315095,8.6625,,S
1162,0,1,"McCaffry, Mr. Thomas Francis",male,46,0,0,13050,75.2417,C6,C
1163,0,3,"Fox, Mr. Patrick",male,,0,0,368573,7.75,,Q
1164,1,1,"Clark, Mrs. Walter Miller (Virginia McDowell)",female,26,1,0,13508,136.7792,C89,C
1165,1,3,"Lennon, Miss. Mary",female,,1,0,370371,15.5,,Q
1166,0,3,"Saade, Mr. Jean Nassr",male,,0,0,2676,7.225,,C
1167,1,2,"Bryhl, Miss. Dagmar Jenny Ingeborg ",female,20,1,0,236853,26,,S
1168,0,2,"Parker, Mr. Clifford Richard",male,28,0,0,SC 14888,10.5,,S
1169,0,2,"Faunthorpe, Mr. Harry",male,40,1,0,2926,26,,S
1170,0,2,"Ware, Mr. John James",male,30,1,0,CA 31352,21,,S
1171,0,2,"Oxenham, Mr. Percy Thomas",male,22,0,0,W./C. 14260,10.5,,S
1172,1,3,"Oreskovic, Miss. Jelka",female,23,0,0,315085,8.6625,,S
1173,0,3,"Peacock, Master. Alfred Edward",male,0.75,1,1,SOTON/O.Q. 3101315,13.775,,S
1174,1,3,"Fleming, Miss. Honora",female,,0,0,364859,7.75,,Q
1175,1,3,"Touma, Miss. Maria Youssef",female,9,1,1,2650,15.2458,,C
1176,1,3,"Rosblom, Miss. Salli Helena",female,2,1,1,370129,20.2125,,S
1177,0,3,"Dennis, Mr. William",male,36,0,0,A/5 21175,7.25,,S
1178,0,3,"Franklin, Mr. Charles (Charles Fardon)",male,,0,0,SOTON/O.Q. 3101314,7.25,,S

In [4]:
with open("sample.txt","r") as file:
    content = file.read()
    print(content)

Hello world!

In [30]:
# CSV - comma separated values
with open("Excel_jumia 1.csv","r") as file:
    content = file.read()
    print (content)

Product,Current price,old price,Discount,Review,Ratingd
115  Piece Set Of Multifunctional Precision Screwdrivers,KSh 950,"KSh 1,525",38%,-2,4.5 out of 5
Metal Decorative Hooks Key Hangers Entryway Wall Hooks Towel Hooks - Home,KSh 527,KSh 999,47%,-14,4.1 out of 5
Portable Mini Cordless Car Vacuum Cleaner - Blue,"KSh 2,199","KSh 2,923",25%,-24,4.6 out of 5
Weighing Scale Digital Bathroom Body Fat Scale USB-Black,"KSh 1,580","KSh 2,499",37%,-7,4.7 out of 5
Portable Home Small Air Humidifier 3-Speed Fan - Green,"KSh 1,740","KSh 2,356",26%,-5,4.8 out of 5
"220V 60W Electric Soldering Iron Kits With Tools, Tips, And Multimeter","KSh 2,999","KSh 3,290",9%,-15,4 out of 5
137 Pieces Cake Decorating Tool Set Baking Supplies,"KSh 2,319","KSh 3,032",24%,-55,4.6 out of 5
Desk Foldable Fan Adjustable Fan Strong Wind 3 Gear Usb,KSh 988,"KSh 1,580",37%,-2,4 out of 5
LASA FOLDING TABLE SERVING STAND,"KSh 1,274","KSh 2,800",55%,-5,4.8 out of 5
13 In 1 Home Repair Tools Box Kit Set,"KSh 1,600","KSh 2,929",45%,-5,3.8 out of 5
Genebre 115 In 1 Screwdriver Repairing Tool Set For IPhone Cellphone Hand Tool,KSh 799,KSh 999,20%,-12,4.1 out of 5
100 Pcs Crochet Hook Tool Set Knitting Hook Set With Box,KSh 990,"KSh 1,500",34%,-39,4.7 out of 5
40cm Gold DIY Acrylic Wall Sticker Clock,KSh 552,"KSh 1,035",47%,-12,4.8 out of 5
LASA Digital Thermometer And Hydrometer,KSh 501,KSh 860,42%,-6,4.5 out of 5
Multifunction Laser Level With Adjustment Tripod,"KSh 1,680","KSh 2,499",33%,-9,4.2 out of 5
Anti-Skid Absorbent Insulation Coaster  For Home Office,KSh 332,KSh 684,51%,-2,5 out of 5
Peacock  Throw Pillow Cushion Case For Home Car,KSh 195,KSh 360,46%,-2,5 out of 5
LASA Aluminum Folding Truck Hand Cart - 68kg Max,"KSh 2,025","KSh 3,971",49%,-3,5 out of 5
LED Wall Digital Alarm Clock Study Home 12 / 24H Clock Calendar,"KSh 2,999","KSh 3,699",19%,-5,4.6 out of 5
3D Waterproof EVA Plastic Shower Curtain 1.8*2Mtrs,KSh 998,"KSh 1,966",49%,-44,4.6 out of 5
3PCS Single Head Knitting Crochet Sweater Needle Set,KSh 38,KSh 80,53%,-13,3.3 out of 5
"4pcs Bathroom/Kitchen Towel Rack,Roll Paper Holder,Towel Bars,Hook","KSh 1,860","KSh 3,220",42%,,
"LED Romantic Spaceship Starry Sky Projector,Children's Bedroom Night Light-Blue",KSh 880,"KSh 1,350",35%,-6,4 out of 5
Foldable Overbed Table/Desk,"KSh 1,650","KSh 2,150",23%,-14,4.4 out of 5
LASA 3 Tier Bamboo Shoe Bench Storage Shelf,"KSh 2,048","KSh 4,500",54%,-7,4.3 out of 5
Electronic Digital Display Vernier Caliper,KSh 420,KSh 647,35%,-49,4.6 out of 5
Portable Wardrobe Nonwoven With 3 Hanging Rods And 6 Storage Shelves,"KSh 2,880","KSh 3,520",18%,-12,3.8 out of 5
12 Litre Black Insulated Lunch Box,"KSh 1,350","KSh 1,990",32%,-13,3.8 out of 5
52 Pieces Cake Decorating Tool Set Gift Kit Baking Supplies,"KSh 1,758","KSh 2,499",30%,-20,4.1 out of 5
MultiFunctional Storage Rack Multi-layer Bookshelf,"KSh 2,200","KSh 4,080",46%,,
Exfoliate And Exfoliate Face Towel - Black,KSh 185,KSh 382,52%,-9,4.3 out of 5
12 Litre Insulated Lunch Box Grey,KSh 980,"KSh 1,490",34%,-12,4.7 out of 5
"LED Eye Protection  Desk Lamp , Study, Reading, USB Fan - Double Pen Holder","KSh 1,820","KSh 3,490",48%,-9,4.3 out of 5
53Pcs/Set Yarn Knitting Crochet Hooks With Bag - Fortune Cat,"KSh 1,940","KSh 2,650",27%,-20,4.7 out of 5
53 Pieces/Set Yarn Knitting Crochet Hooks With Bag - Pansies,"KSh 1,980","KSh 2,699",27%,-32,4.5 out of 5
"DIY File Folder, Office Drawer File Holder, Pen Holder, Desktop Storage Rack","KSh 1,620","KSh 2,690",40%,-1,5 out of 5
Classic Black Cat Cotton Hemp Pillow Case For Home Car,KSh 171,KSh 360,53%,-2,5 out of 5
Punch-free Great Load Bearing Bathroom Storage Rack Wall Shelf-White,KSh 389,KSh 656,41%,-36,4.3 out of 5
"1/2/3 Seater Elastic Sofa Cover,Living Room/Home Decor Chair Cover-Grey","KSh 1,620 - KSh 1,980","KSh 2,200 - KSh 3,200",38%,-2,4.5 out of 5
LASA Stainless Steel Double Wall Mount Soap Dispenser - 500ml,"KSh 2,750","KSh 4,471",38%,,
4M Float Switch Water Level Controller -Water Tank,KSh 475,KSh 931,49%,,
Modern Sofa Throw Pillow Cover-45x45cm-Blue&Red,KSh 238,KSh 476,50%,,
"Balloon Insert, Birthday Party Balloon Set, PU Leather",KSh 610,"KSh 1,060",42%,,
"Balloon Insert, Birthday Party Balloon Set, PU Leather",KSh 610,"KSh 1,060",42%,,
Shower Cap Wide Elastic Band Cover Reusable Bashroom Cap,"KSh 2,132","KSh 2,169",2%,,
Christmas Elk Fence Yard Lawn Decorations Cute For Holidays,KSh 999,"KSh 2,000",50%,,
60W Hot Melt Glue Sprayer - Efficient And Stable Glue Dispensing,"KSh 1,190","KSh 1,785",33%,,
Car Phone Charging Stand,KSh 671,"KSh 1,316",49%,,
2pcs Solar Street Light Flood Light Outdoor,"KSh 1,200","KSh 1,950",38%,,
Creative Owl Shape Keychain Black,KSh 199,KSh 504,61%,,
Brush & Paintbrush Cleaning Tool Pink,KSh 299,KSh 600,50%,,
Pen Grips For Kids Pen Grip Posture Correction Tool For Kids,"KSh 1,660","KSh 1,699",2%,,
Pilates Cloth Bag Waterproof Durable High Capacity Purple,KSh 299,KSh 384,22%,,
Multi-purpose Rice Drainage Basket And Fruit And Vegetable Drainage Sieve,"KSh 1,459","KSh 1,499",3%,,
Cute Christmas Fence Garden Decorations For Holiday Home,KSh 799,"KSh 1,343",41%,,
Simple Metal Dog Art Sculpture Decoration For Home Office,KSh 499,KSh 900,45%,,
Christmas Fence Garden Decorations Outdoor For Holiday Home,KSh 699,"KSh 1,343",48%,,
Angle Measuring Tool Full Metal Multi Angle Measuring Tool,KSh 799,"KSh 1,567",49%,,
12V 19500rpm Handheld Electric Angle Grinder Tool - UK - Yellow/Black,"KSh 2,799","KSh 3,810",27%,,
Simple Metal Dog Art Sculpture Decoration For Home Office,KSh 399,KSh 896,55%,,
5 Pieces/set Of Stainless Steel Induction Cooker Pots,"KSh 2,170","KSh 2,500",13%,-6,2.5 out of 5
Mythco 120COB Solar Wall Ligt With Motion Sensor And Remote Control 3 Modes,KSh 458,KSh 986,54%,-10,3 out of 5
5-PCS Stainless Steel Cooking Pot Set With Steamed Slices,"KSh 2,115","KSh 4,700",55%,-13,2.1 out of 5
120W Cordless Vacuum Cleaners Handheld Electric Vacuum Cleaner,KSh 445,KSh 873,49%,-69,2.8 out of 5
Intelligent  LED Body Sensor Wireless Lighting Night Light USB,KSh 325,KSh 680,52%,-15,2.7 out of 5
VIC Wireless Vacuum Cleaner Dual Use For Home And Car 120W High Power Powerful,"KSh 1,220","KSh 1,555",22%,-16,2.9 out of 5
Artificial Potted Flowers Room Decorative Flowers (2 Pieces),KSh 990,"KSh 1,814",45%,-6,2.2 out of 5
380ML USB Rechargeable Portable Small Blenders And Juicers,"KSh 1,000","KSh 2,000",50%,-7,2.3 out of 5
32PCS Portable Cordless Drill Set With Cyclic Battery Drive -26 Variable Speed,"KSh 3,750","KSh 6,143",39%,-5,3 out of 5
Agapeon Toothbrush Holder And Toothpaste Dispenser,KSh 382,KSh 700,45%,-17,2.6 out of 5
Large Lazy Inflatable Sofa Chairs PVC Lounger Seat Bag,"KSh 2,300","KSh 3,240",29%,-5,3 out of 5
Watercolour Gold Foil Textured Print Pillow Cover,KSh 345,KSh 602,43%,-6,2.3 out of 5
Wrought Iron Bathroom Shelf Wall Mounted Free Punch Toilet Rack,KSh 509,KSh 899,43%,-5,3 out of 5
"7-piece Set Of Storage Bags, Travel Storage Bags, Shoe Bags",KSh 968,"KSh 1,814",47%,-6,2.2 out of 5
"Electric LED UV Mosquito Killer Lamp, Outdoor/Indoor Fly Killer Trap Light -USB","KSh 1,570","KSh 2,988",47%,-7,2.1 out of 5
2PCS/LOT Solar LED Outdoor Intelligent Light Controlled Wall Lamp,KSh 790,"KSh 1,485",47%,,
3PCS Rotary Scraper Thermomix For Kitchen,KSh 690,"KSh 1,200",43%,,
Cushion Silicone Butt Cushion Summer Ice Cushion Honeycomb Gel Cushion,"KSh 1,732","KSh 1,799",4%,,
7PCS Silicone Thumb Knife Finger Protector Vegetable Harvesting Knife,KSh 230,KSh 450,49%,,
"Memory Foam Neck Pillow Cover, With Pillow Core - 50*30cm","KSh 1,189","KSh 2,199",46%,-1,3 out of 5
Bedroom Simple Floor Hanging Clothes Rack Single Pole Hat Rack - White,KSh 979,"KSh 1,920",49%,-1,5 out of 5
5m Waterproof Spherical LED String Lights Outdoor Ball Chain Lights Party Lighting Decoration Adjustable,"KSh 1,460","KSh 2,290",36%,,
2 Pairs Cowhide Split Leather Work Gloves.32â„‰ Or Above Welding Gloves,"KSh 1,666","KSh 1,699",2%,,
Household Pineapple Peeler Peeler,KSh 330,KSh 647,49%,-1,4 out of 5
"Balloon Insert, Birthday Party Balloon Set, PU Leather",KSh 610,"KSh 1,060",42%,,
Creative Owl Shape Keychain Black,KSh 176,KSh 345,49%,,
Office Chair Lumbar Back Support Spine Posture Correction Pillow Car Cushion,"KSh 1,466","KSh 1,699",14%,,
Cartoon Car Decoration Cute Individuality For Car Home Desk,KSh 274,KSh 537,49%,,
Outdoor Portable Water Bottle With Medicine Box - 600ML - Black,KSh 799,KSh 900,11%,,
Angle Measuring Tool Full Metal Multi Angle Measuring Tool,KSh 657,"KSh 1,288",49%,,
Wall-Mounted Toothbrush Toothpaste Holder With Multiple Slots,"KSh 1,468","KSh 1,699",14%,,
Multifunctional Hanging Storage Box Storage Bag (4 Layers),KSh 630,"KSh 1,100",43%,,
Wall Clock With Hidden Safe Box,KSh 850,"KSh 1,700",50%,,
Portable Wine Table With Folding Round Table,"KSh 1,300","KSh 2,500",48%,,
Sewing Machine Needle Threader Stitch Insertion Tool Automatic Quick Sewing,KSh 105,KSh 200,48%,,
6 Layers Steel Pipe Assembling Dustproof Storage Shoe Cabinet,KSh 899,"KSh 1,699",47%,,
6 Layers Steel Pipe Assembling Dustproof Storage Shoe Cabinet,KSh 899,"KSh 1,699",47%,,
2PCS Ice Silk Square Cushion Cover Pillowcases - 65x65cm,"KSh 1,200","KSh 2,400",50%,,
Wall Mount Automatic Toothpaste Dispenser Toothbrush Holder Toothpaste Squeezer,"KSh 1,526","KSh 1,660",8%,,
Portable Soap Dispenser Kitchen Detergent Press Box Kitchen Tools,"KSh 1,462","KSh 1,499",2%,,
4 Piece Coloured Stainless Steel Kitchenware Set,KSh 248,KSh 486,49%,,
Metal Wall Clock Silver Dial Crystal Jewelry Round Home Decoration Wall Clock,"KSh 3,546","KSh 3,699",4%,,
Baby Early Education Shape And Color Cognitive Training Toys,KSh 525,"KSh 1,029",49%,,
8in1 Screwdriver With LED Light,"KSh 1,080","KSh 1,874",42%,,
"Konka Healty Electric Kettle, 24-hour Heat Preservation,1.5L,800W, White","KSh 3,640","KSh 4,588",21%,-1,5 out of 5
"9pcs Gas Mask, For Painting, Dust, Formaldehyde Grinding, Polishing","KSh 1,420","KSh 2,420",41%,,
24 Grid Wall-mounted Sundries Organiser Fabric Closet Bag Storage Rack,"KSh 1,875","KSh 1,899",1%,,
1PC Refrigerator Food Seal Pocket Fridge Bags,KSh 198,KSh 260,24%,,
LED Solar Street Light-fake Camera,"KSh 1,150","KSh 1,737",34%,,
Cartoon Embroidered Mini Towel Bear Cotton Wash Cloth Hand 4pcs,"KSh 1,190","KSh 1,810",34%,,
Shower Nozzle Cleaning Unclogging Needle Mini Crevice Small Hole Cleaning Brush,"KSh 1,658","KSh 1,699",2%,,
Thickening Multipurpose Non Stick Easy To Clean Heat Resistant Spoon Pad,"KSh 1,768","KSh 1,799",2%,,
6 In 1 Bottle Can Opener Multifunctional Easy Opener,KSh 199,KSh 553,64%,,
Wall-mounted Sticker Punch-free Plug Fixer,KSh 450,KSh 900,50%,-1,2 out of 5
Black Simple Water Cup Wine Coaster Anti Slip Absorbent,KSh 169,KSh 320,47%,,

In [37]:
with open("sample.csv","r") as file:
    content = file.read()
    print(content)

In [40]:
with open("Excel_jumia 1.csv","r") as file:
    content = file.read()
    print(content)

Product,Current price,old price,Discount,Review,Ratingd
115  Piece Set Of Multifunctional Precision Screwdrivers,KSh 950,"KSh 1,525",38%,-2,4.5 out of 5
Metal Decorative Hooks Key Hangers Entryway Wall Hooks Towel Hooks - Home,KSh 527,KSh 999,47%,-14,4.1 out of 5
Portable Mini Cordless Car Vacuum Cleaner - Blue,"KSh 2,199","KSh 2,923",25%,-24,4.6 out of 5
Weighing Scale Digital Bathroom Body Fat Scale USB-Black,"KSh 1,580","KSh 2,499",37%,-7,4.7 out of 5
Portable Home Small Air Humidifier 3-Speed Fan - Green,"KSh 1,740","KSh 2,356",26%,-5,4.8 out of 5
"220V 60W Electric Soldering Iron Kits With Tools, Tips, And Multimeter","KSh 2,999","KSh 3,290",9%,-15,4 out of 5
137 Pieces Cake Decorating Tool Set Baking Supplies,"KSh 2,319","KSh 3,032",24%,-55,4.6 out of 5
Desk Foldable Fan Adjustable Fan Strong Wind 3 Gear Usb,KSh 988,"KSh 1,580",37%,-2,4 out of 5
LASA FOLDING TABLE SERVING STAND,"KSh 1,274","KSh 2,800",55%,-5,4.8 out of 5
13 In 1 Home Repair Tools Box Kit Set,"KSh 1,600","KSh 2,929",45%,-5,3.8 out of 5
Genebre 115 In 1 Screwdriver Repairing Tool Set For IPhone Cellphone Hand Tool,KSh 799,KSh 999,20%,-12,4.1 out of 5
100 Pcs Crochet Hook Tool Set Knitting Hook Set With Box,KSh 990,"KSh 1,500",34%,-39,4.7 out of 5
40cm Gold DIY Acrylic Wall Sticker Clock,KSh 552,"KSh 1,035",47%,-12,4.8 out of 5
LASA Digital Thermometer And Hydrometer,KSh 501,KSh 860,42%,-6,4.5 out of 5
Multifunction Laser Level With Adjustment Tripod,"KSh 1,680","KSh 2,499",33%,-9,4.2 out of 5
Anti-Skid Absorbent Insulation Coaster  For Home Office,KSh 332,KSh 684,51%,-2,5 out of 5
Peacock  Throw Pillow Cushion Case For Home Car,KSh 195,KSh 360,46%,-2,5 out of 5
LASA Aluminum Folding Truck Hand Cart - 68kg Max,"KSh 2,025","KSh 3,971",49%,-3,5 out of 5
LED Wall Digital Alarm Clock Study Home 12 / 24H Clock Calendar,"KSh 2,999","KSh 3,699",19%,-5,4.6 out of 5
3D Waterproof EVA Plastic Shower Curtain 1.8*2Mtrs,KSh 998,"KSh 1,966",49%,-44,4.6 out of 5
3PCS Single Head Knitting Crochet Sweater Needle Set,KSh 38,KSh 80,53%,-13,3.3 out of 5
"4pcs Bathroom/Kitchen Towel Rack,Roll Paper Holder,Towel Bars,Hook","KSh 1,860","KSh 3,220",42%,,
"LED Romantic Spaceship Starry Sky Projector,Children's Bedroom Night Light-Blue",KSh 880,"KSh 1,350",35%,-6,4 out of 5
Foldable Overbed Table/Desk,"KSh 1,650","KSh 2,150",23%,-14,4.4 out of 5
LASA 3 Tier Bamboo Shoe Bench Storage Shelf,"KSh 2,048","KSh 4,500",54%,-7,4.3 out of 5
Electronic Digital Display Vernier Caliper,KSh 420,KSh 647,35%,-49,4.6 out of 5
Portable Wardrobe Nonwoven With 3 Hanging Rods And 6 Storage Shelves,"KSh 2,880","KSh 3,520",18%,-12,3.8 out of 5
12 Litre Black Insulated Lunch Box,"KSh 1,350","KSh 1,990",32%,-13,3.8 out of 5
52 Pieces Cake Decorating Tool Set Gift Kit Baking Supplies,"KSh 1,758","KSh 2,499",30%,-20,4.1 out of 5
MultiFunctional Storage Rack Multi-layer Bookshelf,"KSh 2,200","KSh 4,080",46%,,
Exfoliate And Exfoliate Face Towel - Black,KSh 185,KSh 382,52%,-9,4.3 out of 5
12 Litre Insulated Lunch Box Grey,KSh 980,"KSh 1,490",34%,-12,4.7 out of 5
"LED Eye Protection  Desk Lamp , Study, Reading, USB Fan - Double Pen Holder","KSh 1,820","KSh 3,490",48%,-9,4.3 out of 5
53Pcs/Set Yarn Knitting Crochet Hooks With Bag - Fortune Cat,"KSh 1,940","KSh 2,650",27%,-20,4.7 out of 5
53 Pieces/Set Yarn Knitting Crochet Hooks With Bag - Pansies,"KSh 1,980","KSh 2,699",27%,-32,4.5 out of 5
"DIY File Folder, Office Drawer File Holder, Pen Holder, Desktop Storage Rack","KSh 1,620","KSh 2,690",40%,-1,5 out of 5
Classic Black Cat Cotton Hemp Pillow Case For Home Car,KSh 171,KSh 360,53%,-2,5 out of 5
Punch-free Great Load Bearing Bathroom Storage Rack Wall Shelf-White,KSh 389,KSh 656,41%,-36,4.3 out of 5
"1/2/3 Seater Elastic Sofa Cover,Living Room/Home Decor Chair Cover-Grey","KSh 1,620 - KSh 1,980","KSh 2,200 - KSh 3,200",38%,-2,4.5 out of 5
LASA Stainless Steel Double Wall Mount Soap Dispenser - 500ml,"KSh 2,750","KSh 4,471",38%,,
4M Float Switch Water Level Controller -Water Tank,KSh 475,KSh 931,49%,,
Modern Sofa Throw Pillow Cover-45x45cm-Blue&Red,KSh 238,KSh 476,50%,,
"Balloon Insert, Birthday Party Balloon Set, PU Leather",KSh 610,"KSh 1,060",42%,,
"Balloon Insert, Birthday Party Balloon Set, PU Leather",KSh 610,"KSh 1,060",42%,,
Shower Cap Wide Elastic Band Cover Reusable Bashroom Cap,"KSh 2,132","KSh 2,169",2%,,
Christmas Elk Fence Yard Lawn Decorations Cute For Holidays,KSh 999,"KSh 2,000",50%,,
60W Hot Melt Glue Sprayer - Efficient And Stable Glue Dispensing,"KSh 1,190","KSh 1,785",33%,,
Car Phone Charging Stand,KSh 671,"KSh 1,316",49%,,
2pcs Solar Street Light Flood Light Outdoor,"KSh 1,200","KSh 1,950",38%,,
Creative Owl Shape Keychain Black,KSh 199,KSh 504,61%,,
Brush & Paintbrush Cleaning Tool Pink,KSh 299,KSh 600,50%,,
Pen Grips For Kids Pen Grip Posture Correction Tool For Kids,"KSh 1,660","KSh 1,699",2%,,
Pilates Cloth Bag Waterproof Durable High Capacity Purple,KSh 299,KSh 384,22%,,
Multi-purpose Rice Drainage Basket And Fruit And Vegetable Drainage Sieve,"KSh 1,459","KSh 1,499",3%,,
Cute Christmas Fence Garden Decorations For Holiday Home,KSh 799,"KSh 1,343",41%,,
Simple Metal Dog Art Sculpture Decoration For Home Office,KSh 499,KSh 900,45%,,
Christmas Fence Garden Decorations Outdoor For Holiday Home,KSh 699,"KSh 1,343",48%,,
Angle Measuring Tool Full Metal Multi Angle Measuring Tool,KSh 799,"KSh 1,567",49%,,
12V 19500rpm Handheld Electric Angle Grinder Tool - UK - Yellow/Black,"KSh 2,799","KSh 3,810",27%,,
Simple Metal Dog Art Sculpture Decoration For Home Office,KSh 399,KSh 896,55%,,
5 Pieces/set Of Stainless Steel Induction Cooker Pots,"KSh 2,170","KSh 2,500",13%,-6,2.5 out of 5
Mythco 120COB Solar Wall Ligt With Motion Sensor And Remote Control 3 Modes,KSh 458,KSh 986,54%,-10,3 out of 5
5-PCS Stainless Steel Cooking Pot Set With Steamed Slices,"KSh 2,115","KSh 4,700",55%,-13,2.1 out of 5
120W Cordless Vacuum Cleaners Handheld Electric Vacuum Cleaner,KSh 445,KSh 873,49%,-69,2.8 out of 5
Intelligent  LED Body Sensor Wireless Lighting Night Light USB,KSh 325,KSh 680,52%,-15,2.7 out of 5
VIC Wireless Vacuum Cleaner Dual Use For Home And Car 120W High Power Powerful,"KSh 1,220","KSh 1,555",22%,-16,2.9 out of 5
Artificial Potted Flowers Room Decorative Flowers (2 Pieces),KSh 990,"KSh 1,814",45%,-6,2.2 out of 5
380ML USB Rechargeable Portable Small Blenders And Juicers,"KSh 1,000","KSh 2,000",50%,-7,2.3 out of 5
32PCS Portable Cordless Drill Set With Cyclic Battery Drive -26 Variable Speed,"KSh 3,750","KSh 6,143",39%,-5,3 out of 5
Agapeon Toothbrush Holder And Toothpaste Dispenser,KSh 382,KSh 700,45%,-17,2.6 out of 5
Large Lazy Inflatable Sofa Chairs PVC Lounger Seat Bag,"KSh 2,300","KSh 3,240",29%,-5,3 out of 5
Watercolour Gold Foil Textured Print Pillow Cover,KSh 345,KSh 602,43%,-6,2.3 out of 5
Wrought Iron Bathroom Shelf Wall Mounted Free Punch Toilet Rack,KSh 509,KSh 899,43%,-5,3 out of 5
"7-piece Set Of Storage Bags, Travel Storage Bags, Shoe Bags",KSh 968,"KSh 1,814",47%,-6,2.2 out of 5
"Electric LED UV Mosquito Killer Lamp, Outdoor/Indoor Fly Killer Trap Light -USB","KSh 1,570","KSh 2,988",47%,-7,2.1 out of 5
2PCS/LOT Solar LED Outdoor Intelligent Light Controlled Wall Lamp,KSh 790,"KSh 1,485",47%,,
3PCS Rotary Scraper Thermomix For Kitchen,KSh 690,"KSh 1,200",43%,,
Cushion Silicone Butt Cushion Summer Ice Cushion Honeycomb Gel Cushion,"KSh 1,732","KSh 1,799",4%,,
7PCS Silicone Thumb Knife Finger Protector Vegetable Harvesting Knife,KSh 230,KSh 450,49%,,
"Memory Foam Neck Pillow Cover, With Pillow Core - 50*30cm","KSh 1,189","KSh 2,199",46%,-1,3 out of 5
Bedroom Simple Floor Hanging Clothes Rack Single Pole Hat Rack - White,KSh 979,"KSh 1,920",49%,-1,5 out of 5
5m Waterproof Spherical LED String Lights Outdoor Ball Chain Lights Party Lighting Decoration Adjustable,"KSh 1,460","KSh 2,290",36%,,
2 Pairs Cowhide Split Leather Work Gloves.32â„‰ Or Above Welding Gloves,"KSh 1,666","KSh 1,699",2%,,
Household Pineapple Peeler Peeler,KSh 330,KSh 647,49%,-1,4 out of 5
"Balloon Insert, Birthday Party Balloon Set, PU Leather",KSh 610,"KSh 1,060",42%,,
Creative Owl Shape Keychain Black,KSh 176,KSh 345,49%,,
Office Chair Lumbar Back Support Spine Posture Correction Pillow Car Cushion,"KSh 1,466","KSh 1,699",14%,,
Cartoon Car Decoration Cute Individuality For Car Home Desk,KSh 274,KSh 537,49%,,
Outdoor Portable Water Bottle With Medicine Box - 600ML - Black,KSh 799,KSh 900,11%,,
Angle Measuring Tool Full Metal Multi Angle Measuring Tool,KSh 657,"KSh 1,288",49%,,
Wall-Mounted Toothbrush Toothpaste Holder With Multiple Slots,"KSh 1,468","KSh 1,699",14%,,
Multifunctional Hanging Storage Box Storage Bag (4 Layers),KSh 630,"KSh 1,100",43%,,
Wall Clock With Hidden Safe Box,KSh 850,"KSh 1,700",50%,,
Portable Wine Table With Folding Round Table,"KSh 1,300","KSh 2,500",48%,,
Sewing Machine Needle Threader Stitch Insertion Tool Automatic Quick Sewing,KSh 105,KSh 200,48%,,
6 Layers Steel Pipe Assembling Dustproof Storage Shoe Cabinet,KSh 899,"KSh 1,699",47%,,
6 Layers Steel Pipe Assembling Dustproof Storage Shoe Cabinet,KSh 899,"KSh 1,699",47%,,
2PCS Ice Silk Square Cushion Cover Pillowcases - 65x65cm,"KSh 1,200","KSh 2,400",50%,,
Wall Mount Automatic Toothpaste Dispenser Toothbrush Holder Toothpaste Squeezer,"KSh 1,526","KSh 1,660",8%,,
Portable Soap Dispenser Kitchen Detergent Press Box Kitchen Tools,"KSh 1,462","KSh 1,499",2%,,
4 Piece Coloured Stainless Steel Kitchenware Set,KSh 248,KSh 486,49%,,
Metal Wall Clock Silver Dial Crystal Jewelry Round Home Decoration Wall Clock,"KSh 3,546","KSh 3,699",4%,,
Baby Early Education Shape And Color Cognitive Training Toys,KSh 525,"KSh 1,029",49%,,
8in1 Screwdriver With LED Light,"KSh 1,080","KSh 1,874",42%,,
"Konka Healty Electric Kettle, 24-hour Heat Preservation,1.5L,800W, White","KSh 3,640","KSh 4,588",21%,-1,5 out of 5
"9pcs Gas Mask, For Painting, Dust, Formaldehyde Grinding, Polishing","KSh 1,420","KSh 2,420",41%,,
24 Grid Wall-mounted Sundries Organiser Fabric Closet Bag Storage Rack,"KSh 1,875","KSh 1,899",1%,,
1PC Refrigerator Food Seal Pocket Fridge Bags,KSh 198,KSh 260,24%,,
LED Solar Street Light-fake Camera,"KSh 1,150","KSh 1,737",34%,,
Cartoon Embroidered Mini Towel Bear Cotton Wash Cloth Hand 4pcs,"KSh 1,190","KSh 1,810",34%,,
Shower Nozzle Cleaning Unclogging Needle Mini Crevice Small Hole Cleaning Brush,"KSh 1,658","KSh 1,699",2%,,
Thickening Multipurpose Non Stick Easy To Clean Heat Resistant Spoon Pad,"KSh 1,768","KSh 1,799",2%,,
6 In 1 Bottle Can Opener Multifunctional Easy Opener,KSh 199,KSh 553,64%,,
Wall-mounted Sticker Punch-free Plug Fixer,KSh 450,KSh 900,50%,-1,2 out of 5
Black Simple Water Cup Wine Coaster Anti Slip Absorbent,KSh 169,KSh 320,47%,,

In [42]:
# WRITE THE DATA IN EXCEL FILE TO SAMPLE.CSV
import csv

# Step 1: Open the source file (Excel.csv) for reading
with open('Excel_jumia 1.csv', mode='r', newline='', encoding='utf-8') as infile:
    reader = csv.reader(infile)

# Step 2: Open the destination file (sample.csv) for writing
    with open('sample.csv', mode='w', newline='', encoding='utf-8') as outfile:
        writer = csv.writer(outfile)

# Step 3: Copy each row from the source to the destination
        for row in reader:
            writer.writerow(row)

--- To display the data in tables

In [22]:
import pandas as pd
df=pd.read_csv(r"Excel_jumia 1.csv")
df.head()

,Product,Current price,old price,Discount,Review,Ratingd
0,115 Piece Set Of Multifunctional Precision Sc...,KSh 950,"KSh 1,525",38%,-2.0,4.5 out of 5
1,Metal Decorative Hooks Key Hangers Entryway Wa...,KSh 527,KSh 999,47%,-14.0,4.1 out of 5
2,Portable Mini Cordless Car Vacuum Cleaner - Blue,"KSh 2,199","KSh 2,923",25%,-24.0,4.6 out of 5
3,Weighing Scale Digital Bathroom Body Fat Scale...,"KSh 1,580","KSh 2,499",37%,-7.0,4.7 out of 5
4,Portable Home Small Air Humidifier 3-Speed Fan...,"KSh 1,740","KSh 2,356",26%,-5.0,4.8 out of 5

In [4]:
df = pd.read_csv(r"Excel_jumia 1.csv")
df.tail(10)

,Product,Current price,old price,Discount,Review,Ratingd
105,"9pcs Gas Mask, For Painting, Dust, Formaldehyd...","KSh 1,420","KSh 2,420",41%,NaN,NaN
106,24 Grid Wall-mounted Sundries Organiser Fabric...,"KSh 1,875","KSh 1,899",1%,NaN,NaN
107,1PC Refrigerator Food Seal Pocket Fridge Bags,KSh 198,KSh 260,24%,NaN,NaN
108,LED Solar Street Light-fake Camera,"KSh 1,150","KSh 1,737",34%,NaN,NaN
109,Cartoon Embroidered Mini Towel Bear Cotton Was...,"KSh 1,190","KSh 1,810",34%,NaN,NaN
110,Shower Nozzle Cleaning Unclogging Needle Mini ...,"KSh 1,658","KSh 1,699",2%,NaN,NaN
111,Thickening Multipurpose Non Stick Easy To Clea...,"KSh 1,768","KSh 1,799",2%,NaN,NaN
112,6 In 1 Bottle Can Opener Multifunctional Easy ...,KSh 199,KSh 553,64%,NaN,NaN
113,Wall-mounted Sticker Punch-free Plug Fixer,KSh 450,KSh 900,50%,-1.0,2 out of 5
114,Black Simple Water Cup Wine Coaster Anti Slip ...,KSh 169,KSh 320,47%,NaN,NaN

---To copy the data from excel to sample.csv

In [5]:
# index = false removes the numbering
# our dataset has a variable df
df.to_csv("sample.csv", index=False)

### Pandas
- Pandas is a powerful library for data analysis and is mostly used to manipulate data sets 
- It provides two main data structures:
   - series ....... column
   - dataframe .... table

In [ ]:
# to view a specific number count rows call in function head and input your number otherwise it gives five rows
df = pd.read_csv(r"Excel_jumia 1.csv")
df.tail(10)

,Product,Current price,old price,Discount,Review,Ratingd
105,"9pcs Gas Mask, For Painting, Dust, Formaldehyd...","KSh 1,420","KSh 2,420",41%,NaN,NaN
106,24 Grid Wall-mounted Sundries Organiser Fabric...,"KSh 1,875","KSh 1,899",1%,NaN,NaN
107,1PC Refrigerator Food Seal Pocket Fridge Bags,KSh 198,KSh 260,24%,NaN,NaN
108,LED Solar Street Light-fake Camera,"KSh 1,150","KSh 1,737",34%,NaN,NaN
109,Cartoon Embroidered Mini Towel Bear Cotton Was...,"KSh 1,190","KSh 1,810",34%,NaN,NaN
110,Shower Nozzle Cleaning Unclogging Needle Mini ...,"KSh 1,658","KSh 1,699",2%,NaN,NaN
111,Thickening Multipurpose Non Stick Easy To Clea...,"KSh 1,768","KSh 1,799",2%,NaN,NaN
112,6 In 1 Bottle Can Opener Multifunctional Easy ...,KSh 199,KSh 553,64%,NaN,NaN
113,Wall-mounted Sticker Punch-free Plug Fixer,KSh 450,KSh 900,50%,-1.0,2 out of 5
114,Black Simple Water Cup Wine Coaster Anti Slip ...,KSh 169,KSh 320,47%,NaN,NaN

--- To display information on data set

In [ ]:
# object also string/categorical in info of dataframes 
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 115 entries, 0 to 114
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Product        115 non-null    object
 1   Current price  115 non-null    object
 2   old price      115 non-null    object
 3   Discount       115 non-null    object
 4   Review         57 non-null     float64
 5   Ratingd        57 non-null     object
dtypes: float64(1), object(5)
memory usage: 5.5+ KB

--- Checking for missing values

In [ ]:
#.sum() shows how many are null.
df.isnull().sum()

Product           0
Current price     0
old price         0
Discount          0
Review           58
Ratingd          58
dtype: int64

In [10]:
df.isnull()

     Product  Current price  old price  Discount  Review  Ratingd
0      False          False      False     False   False    False
1      False          False      False     False   False    False
2      False          False      False     False   False    False
3      False          False      False     False   False    False
4      False          False      False     False   False    False
..       ...            ...        ...       ...     ...      ...
110    False          False      False     False    True     True
111    False          False      False     False    True     True
112    False          False      False     False    True     True
113    False          False      False     False   False    False
114    False          False      False     False    True     True

[115 rows x 6 columns]

--- fillna methos is used to fill missing values in columns
--- To drop both columns exclude then place in a list

In [ ]:
# dropna - to drop columns with missing values
# drop - to drop any columns
# axis = 1 deletes columns while axis = 0 deletes rows.
df=df.drop(columns=["Review","Ratingd"],axis=1)
df.head()

,Product,Current price,old price,Discount
0,115 Piece Set Of Multifunctional Precision Sc...,KSh 950,"KSh 1,525",38%
1,Metal Decorative Hooks Key Hangers Entryway Wa...,KSh 527,KSh 999,47%
2,Portable Mini Cordless Car Vacuum Cleaner - Blue,"KSh 2,199","KSh 2,923",25%
3,Weighing Scale Digital Bathroom Body Fat Scale...,"KSh 1,580","KSh 2,499",37%
4,Portable Home Small Air Humidifier 3-Speed Fan...,"KSh 1,740","KSh 2,356",26%

--- rename the column Ratingd to Ratings

In [ ]:
df.rename(columns={"Ratingd":"Rating"}, inplace=True)
df.head()

,Product,Current price,old price,Discount,Review,Rating
0,115 Piece Set Of Multifunctional Precision Sc...,KSh 950,"KSh 1,525",38%,-2.0,4.5 out of 5
1,Metal Decorative Hooks Key Hangers Entryway Wa...,KSh 527,KSh 999,47%,-14.0,4.1 out of 5
2,Portable Mini Cordless Car Vacuum Cleaner - Blue,"KSh 2,199","KSh 2,923",25%,-24.0,4.6 out of 5
3,Weighing Scale Digital Bathroom Body Fat Scale...,"KSh 1,580","KSh 2,499",37%,-7.0,4.7 out of 5
4,Portable Home Small Air Humidifier 3-Speed Fan...,"KSh 1,740","KSh 2,356",26%,-5.0,4.8 out of 5

In [28]:
df.rename(columns={"Rating":"Ratings"}, inplace= True)
df.head()

,Product,Current price,old price,Discount,Review,Ratings
0,115 Piece Set Of Multifunctional Precision Sc...,KSh 950,"KSh 1,525",38%,-2.0,4.5 out of 5
1,Metal Decorative Hooks Key Hangers Entryway Wa...,KSh 527,KSh 999,47%,-14.0,4.1 out of 5
2,Portable Mini Cordless Car Vacuum Cleaner - Blue,"KSh 2,199","KSh 2,923",25%,-24.0,4.6 out of 5
3,Weighing Scale Digital Bathroom Body Fat Scale...,"KSh 1,580","KSh 2,499",37%,-7.0,4.7 out of 5
4,Portable Home Small Air Humidifier 3-Speed Fan...,"KSh 1,740","KSh 2,356",26%,-5.0,4.8 out of 5

### Grouping and Aggregation

In [1]:
import pandas as pd
data = pd.read_csv(r"tested.csv")
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [ ]:
# []--- what you want to groupby
# ()--- categorical or classes
data.groupby("Pclass")["Fare"].sum()

Pclass
1    10087.9918
2     2064.7957
3     2703.7501
Name: Fare, dtype: float64

In [20]:
# grouping by genders
data.groupby("Sex")["PassengerId"].sum()

Sex
female    166712
male      293297
Name: PassengerId, dtype: int64

In [34]:
data.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,418.000000,418.000000,418.000000,332.000000,418.000000,418.000000,417.000000
mean,1100.500000,0.363636,2.265550,30.272590,0.447368,0.392344,35.627188
std,120.810458,0.481622,0.841838,14.181209,0.896760,0.981429,55.907576
min,892.000000,0.000000,1.000000,0.170000,0.000000,0.000000,0.000000
25%,996.250000,0.000000,1.000000,21.000000,0.000000,0.000000,7.895800
50%,1100.500000,0.000000,3.000000,27.000000,0.000000,0.000000,14.454200
75%,1204.750000,1.000000,3.000000,39.000000,1.000000,0.000000,31.500000
max,1309.000000,1.000000,3.000000,76.000000,8.000000,9.000000,512.329200

In [ ]:
# Visualizations
# streamit
# app.py

### Numpy
- it is a file afflicttion method for computing.
- provides a high performance object and tools to work with

In [1]:
numbers = [1,2,3,4,5,6,7,8,9,10]
num = [10,9,8,7,6,5,4,3,2,1]
result = numbers+num
result

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

In [2]:
import numpy as np

In [3]:
numbers_array = np.array(numbers)
numbers_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
num_array = np.array(num)
num_array

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [ ]:
 result = num_array + numbers_array
 result

array([11, 11, 11, 11, 11, 11, 11, 11, 11, 11])

In [7]:
numbers_array.mean()

np.float64(5.5)

In [8]:
numbers_array.sum()

np.int64(55)

In [ ]:
# standard deviation
numbers_array.std()

np.float64(2.8722813232690143)

In [10]:
# variance
numbers_array.var()

np.float64(8.25)

In [ ]:
# mean of age in tested.csv
data["Age"].mean()

np.float64(30.272590361445783)

In [ ]:
males = data[data"Sex")]